// Contains the list of all pages, that are ready to go.
// There are other pages that are not ready to go, but are referenced in the code.
// Those other pages will be ignored when the links are randomly generated via randomise.rb
const labyrinthPages = [
  "../../corridors/1-bit-dots/index.html",
  "../../corridors/ants-marching/index.html",
  "../../corridors/baby-god/index.html",
  "../../corridors/blade-runner/index.html",
  "../../corridors/bsod/index.html",
  "../../corridors/charlotte/index.html",
  "../../corridors/chinatown/index.html",
  "../../corridors/cloudflare/index.html",
  "../../corridors/cow/index.html",
  "../../corridors/crash-test-dummies/index.html",
  "../../corridors/dancing-baby/index.html",
  "../../corridors/everyday/index.html",
  "../../corridors/fire-brigade/index.html",
  "../../corridors/happy/index.html",
  "../../corridors/heart-of-hearts/index.html",
  "../../corridors/i-luv-u/index.html",
  "../../corridors/important-business/index.html",
  "../../corridors/in-utero/index.html",
  "../../corridors/mompster-quest/index.html",
  "../../corridors/othello/index.html",
  "../../corridors/panopticon/index.html",
  "../../corridors/parklife/index.html",
  "../../corridors/piano/index.html",
  "../../corridors/pills/index.html",
  "../../corridors/poem-fragments/index.html",
  "../../corridors/polygon-face/index.html",
  "../../corridors/snakes/index.html",
  "../../corridors/spider-box/index.html",
  "../../corridors/stuntman/index.html",
  "../../corridors/substack/index.html",
  "../../corridors/swapping-circles/index.html",
  "../../corridors/symbolizm/index.html",
  "../../corridors/symbolizma/index.html",
  "../../corridors/symbolizmo/index.html",
  "../../corridors/trine/index.html",
  "../../corridors/tyger/index.html",
  "../../corridors/vertical-lines/index.html",
  "../../corridors/wandering-aengus/index.html",
  "../../corridors/withnail/index.html",
  "../../corridors/zeno/index.html",
  "../../corridors/zodiac/index.html",
];
